#!/usr/bin/env python

import portupdlib.optparser
import portupdlib.version
import signal, sys
from portupdlib.portupd import portupd

ENVIRONMENT = portupdlib.optparser.parse_arguments()
print ENVIRONMENT
PORTUPD = portupd(ENVIRONMENT)

def handler(signum, frame):
   PORTUPD.quit()
   print "Exiting"
   sys.exit()

signal.signal(signal.SIGTERM, handler)
signal.signal(signal.SIGINT, handler)

PORTUPD.main_loop()
