#!/usr/bin/env python

import portupdlib.optparser
from portupdlib.version import APP_VERSION, APP_NAME
import signal, sys, os
from portupdlib.portupd import portupd

if (os.getuid() != 0):
      print "This program must be run as root"
      sys.exit(1)

ENVIRONMENT = portupdlib.optparser.parse_arguments()
PORTUPD = portupd(ENVIRONMENT)

def handler(signum, frame):
   PORTUPD.quit()
   print "Exiting"
   sys.exit()

signal.signal(signal.SIGTERM, handler)
signal.signal(signal.SIGINT, handler)

print "Starting portupd v%s" % APP_VERSION
PORTUPD.main_loop()
